language: go

env:

addons:
  sonarcloud:
    organization: "bi-beacon" # the key of the org you chose at step #3

script:
  - make
  - sonar-scanner

before_install:
  - curl -F "period=5000" -F "color=#AB00FF" "https://api.cilamp.se/v1/${BI_BEACON_SYSTEM_ID}/"

before_script:
  - curl -F "period=5000" -F "color=#0000FF" "https://api.cilamp.se/v1/${BI_BEACON_SYSTEM_ID}/"

after_success:
  - curl -F "color=#00FF00" "https://api.cilamp.se/v1/${BI_BEACON_SYSTEM_ID}/"

after_failure:
  - curl -F "color=#FF0000" "https://api.cilamp.se/v1/${BI_BEACON_SYSTEM_ID}/"
