language: python
python:
   - "3.5"

env:
  global:
     - PIPENV_VENV_IN_PROJECT=1
     - PIPENV_IGNORE_VIRTUALENVS=1
     - PIPENV_NOSPIN=1
    
install:
   - sudo apt-get install -y graphviz
   - pip install pipenv
   - make setup

script:
   - make
